[package]
name = "lefortovo"
version = "0.1.0"
authors = ["callen"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
bytes = "1.0.1"
clap = "2.33.3"
pretty_env_logger = "0.4.0"
reqwest = "0.11.3"
tokio = { version = "1.5.0", features = ["full"] }
