[package]
name = "lefortovo"
version = "0.1.0"
authors = ["callen"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
bytes = "0.5.6"
clap = "2.33.3"
# hyper = "0.13.1"
# hyper-tls = "0.4.1"
pretty_env_logger = "0.4.0"
reqwest = "0.10.7"
tokio = { version = "0.2.22", features = ["full"] }
